### ISSUE TITLE
Meross iot installation

### ISSUE THREAD

**Issue by vincenzo-suraci-ares2t** [ping-localhost/meross-custom-component#1]
Can you provide more details on how to install meross iot in home assistant, in order to satisfy the requirements?

**Comment by hdjweb** [comment]
I too

**Comment by ping-localhost** [comment]
I'll create a ZIP file tonight that contains all the necessary files (and include a README), however, this is not a stable component yet. After a few hours/a day it stops reconnecting and you need to restart Home Assistant to get it working again.

**Comment by ping-localhost** [comment]
@vincenzo-suraci-ares2t @hdjweb currently waiting for https://github.com/albertogeniola/MerossIot/pull/51. After that I should be ready to release a brand new version. :)

**Comment by ping-localhost** [comment]
@vincenzo-suraci-ares2t @hdjweb Please try again with the updated `README.md` and code. 😉

**Comment by zdavis28** [comment]
Does this support the MSG100 Garage Door opener?

**Comment by ping-localhost** [comment]
@zdavis28 It does not. This component only support plugs for now and even that is basic, since I only have the MSS425e (Smart Wi-Fi Surge Protector).

**Comment by ping-localhost** [comment]
I'm closing this question as it has been answered.
